# Generated by Django 4.2.30 on 2026-04-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='teams/banners/')),
                ('training_schedule', models.TextField(blank=True)),
                ('min_faceit_level', models.IntegerField(blank=True, null=True)),
                ('min_gc_level', models.IntegerField(blank=True, null=True)),
                ('is_recruiting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_team', to='players.players')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('entry_fragger', 'Entry Fragger'), ('in_game_leader', 'In Game Leader'), ('support', 'Support'), ('lurker', 'Lurker'), ('rifler', 'Rifler'), ('awper', 'AWPer'), ('star_player', 'Star Player'), ('second_caller', 'Second Caller'), ('coach', 'Coach')], max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='players.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
