# Generated by Django 4.2.30 on 2026-04-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_merge_20260420_0247'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('entry_fragger', 'Entry Fragger'), ('in_game_leader', 'In Game Leader'), ('support', 'Support'), ('lurker', 'Lurker'), ('rifler', 'Rifler'), ('awper', 'AWPer'), ('star_player', 'Star Player'), ('second_caller', 'Second Caller'), ('coach', 'Coach')], default='rifler', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests_sent', to='players.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('entry_fragger', 'Entry Fragger'), ('in_game_leader', 'In Game Leader'), ('support', 'Support'), ('lurker', 'Lurker'), ('rifler', 'Rifler'), ('awper', 'AWPer'), ('star_player', 'Star Player'), ('second_caller', 'Second Caller'), ('coach', 'Coach')], default='rifler', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to='players.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
