# Generated by Django 4.2.30 on 2026-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamrequest_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='trial_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
