# Generated by Django 4.2.30 on 2026-04-16 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_role', models.CharField(blank=True, choices=[('entry_fragger', 'Entry Fragger'), ('in_game_leader', 'In Game Leader'), ('support', 'Support'), ('lurker', 'Lurker'), ('rifler', 'Rifler'), ('awper', 'AWPer'), ('star_player', 'Star Player'), ('second_caller', 'Second Caller'), ('coach', 'Coach')], max_length=50)),
                ('secondary_role', models.CharField(blank=True, choices=[('entry_fragger', 'Entry Fragger'), ('in_game_leader', 'In Game Leader'), ('support', 'Support'), ('lurker', 'Lurker'), ('rifler', 'Rifler'), ('awper', 'AWPer'), ('star_player', 'Star Player'), ('second_caller', 'Second Caller'), ('coach', 'Coach')], max_length=50)),
                ('tertiary_role', models.CharField(blank=True, choices=[('entry_fragger', 'Entry Fragger'), ('in_game_leader', 'In Game Leader'), ('support', 'Support'), ('lurker', 'Lurker'), ('rifler', 'Rifler'), ('awper', 'AWPer'), ('star_player', 'Star Player'), ('second_caller', 'Second Caller'), ('coach', 'Coach')], max_length=50)),
                ('gamers_club_level', models.IntegerField(blank=True, null=True)),
                ('faceit_level', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_team_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
