# Generated by Django 4.2.30 on 2026-04-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='nationality',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
