# Generated by Django 4.2.30 on 2026-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='players',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='players',
            name='looking_for_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='players',
            name='steam',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='players',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
