# Generated by Django 4.2.30 on 2026-04-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='nationality',
        ),
    ]
