# Generated by Django 4.2.30 on 2026-04-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_banner_players_instagram_and_more'),
        ('players', '0003_remove_nationality'),
    ]

    operations = [
    ]
